import {
  boolean,
  coordinate,
  enumeration,
  nullable,
  number,
  point,
  record,
  revision,
  u32,
} from "./schema.js";

/** Versioned web IDs, not native packet numbers. Body actions from Character.wz:00002000.img
 * and life actions from all 735 maps in the packaged catalog. currency0..3 select
 * catalog.ui.dropArtwork.variants; new content names require a rules/build cutover. */
export const ANIMATION_ACTIONS = Object.freeze([
  "stand1",
  "walk1",
  "jump",
  "prone",
  "ladder",
  "rope",
  "fly",
  "sit",
  "stand2",
  "walk2",
  "alert",
  "heal",
  "swingO1",
  "swingO2",
  "swingO3",
  "swingOF",
  "swingT1",
  "swingT2",
  "swingT3",
  "swingTF",
  "swingP1",
  "swingP2",
  "swingPF",
  "stabO1",
  "stabO2",
  "stabOF",
  "stabT1",
  "stabT2",
  "stabTF",
  "shoot1",
  "shoot2",
  "shootF",
  "shot",
  "proneStab",
  "dead",
  "move",
  "stand",
  "hit1",
  "hit2",
  "die1",
  "die2",
  "attack1",
  "attack2",
  "attack3",
  "attack4",
  "skill1",
  "skill2",
  "skill3",
  "skill4",
  "regen",
  "currency0",
  "currency1",
  "currency2",
  "currency3",
  "act",
  "act0",
  "act1",
  "act2",
  "act2156",
  "act3110",
  "act9803",
  "action",
  "airstrike",
  "alert2",
  "alert3",
  "alert4",
  "alert5",
  "alert6",
  "angry",
  "arm",
  "arm1",
  "arm2",
  "arms",
  "assassination",
  "assaulter",
  "avenger",
  "babari",
  "backspin",
  "backstep",
  "bag",
  "bamboo",
  "bewildered",
  "blackShadow",
  "blade",
  "blast",
  "blink",
  "blizzard",
  "bomb",
  "book",
  "brandish1",
  "brandish2",
  "breath",
  "brow",
  "brows",
  "burster1",
  "burster2",
  "cane",
  "cannon",
  "chainlightning",
  "chase",
  "chew",
  "cold",
  "combatStep",
  "comboFenrir",
  "comboSmash",
  "comboTempest",
  "coolingeffect",
  "cough",
  "cry",
  "cute",
  "darksight",
  "deep",
  "default",
  "demolition",
  "doubleSwing",
  "doublefire",
  "doubleupper",
  "dragonstrike",
  "eburster",
  "edrain",
  "eorb",
  "eye",
  "eyebrow",
  "eyebrows",
  "face",
  "fake",
  "finalBlow",
  "finalCharge",
  "finalToss",
  "finger",
  "fire",
  "fireburner",
  "firestrike",
  "fish",
  "fist",
  "flamegear",
  "float",
  "foot",
  "fullSwingDouble",
  "fullSwingTriple",
  "genesis",
  "glass",
  "gun",
  "hair",
  "hand",
  "hat",
  "head",
  "heart",
  "holyshield",
  "homing",
  "image",
  "incense",
  "joggle",
  "ladder2",
  "lag",
  "laugh",
  "letter",
  "light",
  "lip",
  "magic",
  "magic1",
  "magic2",
  "magic3",
  "magic5",
  "medalcase",
  "melong",
  "memo",
  "meteor",
  "mouse",
  "neon",
  "ninjastorm",
  "nose",
  "observation",
  "observation_",
  "octopus",
  "overSwingDouble",
  "overSwingTriple",
  "paralyze",
  "point",
  "prone2",
  "proud",
  "pyramid",
  "q7221",
  "quest",
  "recovery",
  "regen1",
  "regen2",
  "resurrection",
  "rollingSpin",
  "rope2",
  "rub",
  "rush",
  "rush2",
  "salute",
  "sanctuary",
  "savage",
  "say",
  "say0",
  "say1",
  "say2",
  "say2_",
  "scauter",
  "scissors",
  "scratch",
  "screw",
  "shade",
  "shake",
  "shine",
  "shockwave",
  "shoot",
  "shoot6",
  "shop",
  "shoulder",
  "showdown",
  "shy",
  "side",
  "sigh",
  "smell",
  "smile",
  "smile0",
  "smile1",
  "smokeshell",
  "snatch",
  "snuffle",
  "somersault",
  "souldriver",
  "speak",
  "stand2_",
  "stand_old",
  "stick",
  "stormbreak",
  "straight",
  "swing",
  "swingP1PoleArm",
  "swingP2PoleArm",
  "swingT2PoleArm",
  "tail",
  "tale",
  "talk",
  "tea",
  "throw",
  "timeleap",
  "torpedo",
  "tripleSwing",
  "triplefire",
  "up",
  "vampire",
  "wave",
  "weak",
  "what",
  "windshot",
  "windspear",
  "wink",
]);
const ACTION_IDS = new Map(
  ANIMATION_ACTIONS.map((name, index) => [name, index]),
);
if (ACTION_IDS.size !== ANIMATION_ACTIONS.length) {
  throw new Error("Duplicate animation action name");
}
export function animationId(name) {
  const id = ACTION_IDS.get(name);
  if (id === undefined) throw new Error("Unsupported animation action");
  return id;
}
export function animationName(id) {
  if (
    !Number.isInteger(id) ||
    Object.is(id, -0) ||
    id < 0 ||
    id >= ANIMATION_ACTIONS.length
  ) {
    throw new Error("Unsupported animation action ID");
  }
  return ANIMATION_ACTIONS[id];
}
export const animation = number(0, ANIMATION_ACTIONS.length - 1);
export const heldSchema = record({
  horizontal: enumeration(-1, 0, 1),
  vertical: enumeration(-1, 0, 1),
  jump: boolean,
  attack: boolean,
});
const scalar = number(-1048576, 1048576, false);
const positive = number(0, 1048576, false);
export const SETTINGS_KEYS = Object.freeze([
  "mass",
  "gravity",
  "drag",
  "forceScale",
  "friction",
  "quantumMs",
  "avatar",
  "walkForce",
  "walkSpeed",
  "walkDrag",
  "slipForce",
  "slipSpeed",
  "floatDrag1",
  "floatDrag2",
  "floatCoefficient",
  "swimForce",
  "swimSpeed",
  "flyForce",
  "flySpeed",
  "gravityAcc",
  "fallSpeed",
  "jumpSpeed",
  "maxFriction",
  "minFriction",
  "swimSpeedDec",
  "flyJumpDec",
  "baseWalkSpeed",
  "baseJumpSpeed",
  "baseSwimSpeed",
  "baseForceScale",
  "baseFriction",
  "baseDrag",
]);
const settingsFields = Object.fromEntries(
  SETTINGS_KEYS.map((key) => [key, positive]),
);
settingsFields.quantumMs = enumeration(30);
settingsFields.avatar = enumeration("original-base-attributes");
export const settingsSchema = record(
  settingsFields,
  (value) =>
    value.minFriction <= value.maxFriction &&
    value.mass > 0 &&
    value.fallSpeed > 0,
);
export const formSchema = record({
  speed: nullable(scalar),
  jump: nullable(scalar),
  swim: scalar,
  fs: nullable(scalar),
  riding: boolean,
});
export const worldMovementSchema = record({
  wingsX: scalar,
  form: nullable(formSchema),
  equipmentFs: positive,
  equipmentSwim: positive,
});
export const landingSchema = record({
  terminalTicks: revision,
  thresholdTicks: revision,
  forbidden: boolean,
  sequence: revision,
  amount: u32,
  facing: enumeration(-1, 1),
});
export const scratchSchema = record({
  previousX: coordinate,
  previousY: coordinate,
  x: coordinate,
  y: coordinate,
  fraction: number(0, 2, false),
  segment: nullable(u32),
  first: nullable(u32),
  last: nullable(u32),
  pendingAir: boolean,
  remainingMs: number(0, 30),
  entryX: coordinate,
  entryY: coordinate,
  entryVx: coordinate,
  entryVy: coordinate,
});
export const diagnosticsSchema = record({
  ticks: revision,
  simulatedMs: revision,
  backlogMs: enumeration(0),
  overload: enumeration(false),
  overloadCount: revision,
  transitionLimit: boolean,
  fault: enumeration(
    null,
    "nonfinite-motion",
    "foothold-transition-limit",
    "original-conveyor-division-by-zero",
  ),
  unsupportedLadderFlags: boolean,
  originalCadenceVerified: boolean,
});
export const MOTION_SCALARS = Object.freeze([
  "x",
  "y",
  "vx",
  "vy",
  "previousX",
  "previousY",
  "state",
  "facing",
  "action",
  "crouching",
  "footholdId",
  "ladderId",
  "position",
  "speed",
  "contactLayer",
  "contactGroup",
  "spaceGroup",
  "horizontalInput",
  "verticalInput",
  "fieldLimit",
  "ignoredFootholdId",
  "accumulatorMs",
  "accumulatorError",
  "groundJumpSequence",
  "jumpRepeatMs",
  "movementLocked",
  "movementMode",
  "baseMode",
]);
export const motionSchema = record({
  x: coordinate,
  y: coordinate,
  vx: coordinate,
  vy: coordinate,
  previousX: coordinate,
  previousY: coordinate,
  state: enumeration("air", "ground", "ladder", "swim", "fly"),
  facing: enumeration(-1, 1),
  action: enumeration(
    "stand1",
    "walk1",
    "jump",
    "prone",
    "ladder",
    "rope",
    "fly",
    "sit",
  ),
  crouching: boolean,
  footholdId: u32,
  ladderId: u32,
  foothold: nullable(u32),
  ladder: nullable(u32),
  seat: nullable(point),
  position: scalar,
  speed: scalar,
  contactLayer: u32,
  contactGroup: u32,
  spaceGroup: u32,
  horizontalInput: enumeration(-1, 0, 1),
  verticalInput: enumeration(-1, 0, 1),
  fieldLimit: u32,
  ignoredFootholdId: u32,
  accumulatorMs: enumeration(0),
  accumulatorError: enumeration(0),
  groundJumpSequence: u32,
  jumpRepeatMs: number(0, 300),
  movementLocked: boolean,
  movementMode: enumeration("air", "swim", "fly"),
  baseMode: enumeration("air", "swim", "fly"),
  worldMovement: worldMovementSchema,
  effectiveSettings: settingsSchema,
  landing: landingSchema,
  contactScratch: scratchSchema,
  diagnostics: diagnosticsSchema,
  held: heldSchema,
});
